server:
  port: 8080 # El frontend solo llama a http://localhost:8080/api/...

spring:
  cloud:
    gateway:
      routes:
        - id: reporte-incendio
          uri: http://report-service:8081
          predicates:
            - Path=/api/reporte-incendio,/api/reporte-incendio/**

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/usuario,/api/usuario/**
            - Path=/api/brigada,/api/brigada/**

        - id: alert-service
          uri: http://alert-service:8083
          predicates:
            - Path=/api/alerta-emergencia,/api/alerta-emergencia/**